@extends('legal.layout', ['pageTitle' => 'Terms & Conditions', 'description' => 'Read the terms for using LogicStrand and its personal knowledge workspace.'])

@section('legal-content')
<p>These terms apply when you visit or use LogicStrand. By creating an account or using the service, you agree to these terms. If you do not agree, do not use the service.</p>

<h2>About the service</h2>
<p>LogicStrand provides a personal workspace for uploading text documents, asking questions about their contents, and reviewing generated answers with cited passages. Features, limits, and availability may change as the service develops.</p>

<h2>Accounts and access</h2>
<p>Provide accurate account information, keep your sign-in credentials private, and tell us promptly if you believe your account has been accessed without permission. You are responsible for activity carried out through your account. Accounts must use a verified email address to access workspace features.</p>

<h2>Your documents and permission to process them</h2>
<p>You retain your rights in the documents and other content you submit. You confirm that you have the rights and authority needed to upload that content and use it with LogicStrand. You give us permission to host, extract, index, search, and process the content only as needed to provide and maintain the requested service. When you ask a question, relevant passages and your question are sent to Groq for answer generation, as described in the <a href="{{ route('privacy') }}">Privacy Policy</a>.</p>
<p>Do not upload content that you are not authorized to share, unlawful content, malicious files, or information that would create an unreasonable security or privacy risk. The current upload flow supports text files and text-based PDFs up to 10 MB per file. Scanned PDFs and OCR are not supported.</p>

<h2>AI-generated answers</h2>
<p>Answers are generated by an AI service from selected passages in your documents. They may be incomplete, inaccurate, or unsuitable for your purpose. Review the cited passages and verify important information independently. LogicStrand does not provide legal, medical, financial, or other professional advice, and answers should not be treated as a substitute for qualified advice.</p>

<h2>Plans, limits, and checkout</h2>
<p>Plan features, usage limits, and access periods are shown on the <a href="{{ route('pricing') }}">Pricing page</a> and in your workspace. Sandbox access lasts seven days from activation. Other periods are shown before activation. We may adjust future prices or plan features; changes will not retroactively alter an active access period already displayed in your account.</p>
<p>The current checkout flow is not connected to a payment processor and does not charge a card. It records plan access and the last four digits displayed in the form. No card number, expiry date, or security code is retained by LogicStrand. Prices shown on the site are informational until real payment processing is introduced.</p>

<h2>Acceptable use and service availability</h2>
<p>Use LogicStrand lawfully and do not interfere with the service, attempt unauthorized access, bypass usage limits, or use the service to distribute malware or abuse another person’s rights. We may suspend or restrict access when reasonably necessary to protect users, the service, or comply with law.</p>
<p>We work to keep LogicStrand available, but do not guarantee uninterrupted or error-free operation. We may change, pause, or discontinue features. We will take reasonable steps to preserve user data during ordinary operation, but you should keep your own copies of important source documents.</p>

<h2>Intellectual property</h2>
<p>LogicStrand’s name, branding, software, and site materials are owned by or licensed to the operating entities. These terms do not transfer ownership to you. You may use the service and its materials only as permitted by these terms and applicable law.</p>

<h2>Disclaimers and liability</h2>
<p>To the extent permitted by applicable law, the service is provided as available without warranties that it will meet every need, produce a particular result, or operate without interruption. Nothing in these terms excludes a right or remedy that cannot lawfully be excluded. To the extent permitted by law, LogicStrand will not be liable for indirect or consequential loss arising from use of the service. These terms do not limit liability where such a limitation is prohibited by law.</p>

<h2>Changes and contact</h2>
<p>We may update these terms as the service changes. The current version and its update date will appear on this page. Continued use after an update takes effect means you accept the updated terms to the extent permitted by law. Questions can be sent to <a href="mailto:support@logicstrand.net">support@logicstrand.net</a>.</p>
@endsection
