<x-layouts::app :title="'Answer'">
    <div class="page-shell workspace-page workspace-answer-page">
        <a href="{{ route('answers.index') }}" class="back-link"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Back to history</a>
        <header class="workspace-heading"><div><span class="page-eyebrow">YOUR WORKSPACE / ANSWER</span><h1>{{ $answer->question }}</h1><p>Asked {{ $answer->created_at->format('F j, Y \\a\\t g:i A') }}</p></div><a href="{{ auth()->user()->planAccess?->isActive() ? route('answers.create') : route('pricing') }}" class="button button-blue">Ask another question <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></header>
        <div class="answer-layout">
            <article class="answer-card workspace-answer-card">
                <div class="answer-card-top"><span class="answer-badge"><i class="fa-solid fa-wand-magic-sparkles" aria-hidden="true"></i> LOGICSTRAND ANSWER</span><span>{{ $answer->citations->count() }} {{ Str::plural('source', $answer->citations->count()) }}</span></div>
                <div class="answer-body" id="answer-text">{{ $answer->answer }}</div>
                <div class="answer-card-actions"><button type="button" data-copy-answer aria-label="Copy answer text"><i class="fa-solid fa-copy" aria-hidden="true"></i> Copy answer</button><a href="#source-passages">Review evidence <i class="fa-solid fa-arrow-down" aria-hidden="true"></i></a><form method="POST" action="{{ route('answers.favorite', $answer) }}">@csrf @method('PATCH')<input type="hidden" name="favorite" value="{{ $answer->is_favorite ? 0 : 1 }}"><button type="submit" aria-pressed="{{ $answer->is_favorite ? 'true' : 'false' }}"><i class="fa-solid fa-star" aria-hidden="true"></i> {{ $answer->is_favorite ? 'Saved' : 'Save answer' }}</button></form><a href="{{ route('answers.export', $answer) }}" class="answer-export-link"><i class="fa-solid fa-file-pdf" aria-hidden="true"></i> Download PDF</a></div>
            </article>
            <aside class="answer-guide"><span class="page-eyebrow">READ WITH CONFIDENCE</span><h2>See the thread.</h2><p>Each source card below shows the passage used to support this answer. Open the original file when you need the full context.</p><div class="answer-guide-line" aria-hidden="true"></div><span>{{ $answer->citations->count() ? 'SOURCE-BACKED' : 'INSUFFICIENT EVIDENCE' }}</span></aside>
        </div>
        <section class="content-card answer-note-card" aria-labelledby="private-note-title"><div class="card-heading"><div><span class="page-eyebrow">JUST FOR YOU</span><h2 id="private-note-title">Private note</h2><p>This note is only visible in your workspace and is excluded from PDF exports unless you choose to include it.</p></div></div><form method="POST" action="{{ route('answers.note', $answer) }}">@csrf @method('PUT')<label for="private-note" class="sr-only">Private note for this answer</label><textarea id="private-note" name="private_note" rows="4" maxlength="5000" placeholder="Add a reminder or context for later">{{ old('private_note', $answer->private_note) }}</textarea>@error('private_note')<p class="field-error" role="alert">{{ $message }}</p>@enderror<button type="submit" class="button button-dark">Save private note</button></form><form method="GET" action="{{ route('answers.export', $answer) }}" class="note-export-option"><label><input type="checkbox" name="include_note" value="1"> Include this private note in this PDF</label><button type="submit" class="row-action">Download with note</button></form></section>
        <section class="source-section" id="source-passages"><div class="card-heading"><div><span class="page-eyebrow">FOLLOW THE EVIDENCE</span><h2>Source passages</h2></div><span class="count-pill">{{ $answer->citations->count() }} passages</span></div>
            @forelse($answer->citations as $citation)
                <article class="source-card"><div class="source-card-top"><span class="source-number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><strong>{{ $citation->chunk->document->name }}</strong><small>{{ $citation->chunk->page ? 'Page '.$citation->chunk->page : 'Text document' }}</small></div><a href="{{ route('documents.download', $citation->chunk->document) }}">Download source <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div><p>{{ $citation->chunk->body }}</p></article>
            @empty
                <div class="empty-small"><strong>No supporting passage found.</strong><p>Try a more specific question or add another document.</p><a href="{{ auth()->user()->planAccess?->isActive() ? route('answers.create') : route('pricing') }}">Ask another question <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div>
            @endforelse
        </section>
    </div>
</x-layouts::app>
